name: Convert Markdown to PDF and DOCX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra

      - name: Create output directory
        run: mkdir -p latest-output

      - name: Add timestamp and commit hash to CV
        run: |
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Create a temporary CV with timestamp and commit info
          cp cv.md temp_cv.md
          echo "" >> temp_cv.md
          echo "---" >> temp_cv.md
          echo "" >> temp_cv.md
          echo "*Last updated: ${TIMESTAMP} | Commit: ${COMMIT_HASH}*" >> temp_cv.md

      - name: Convert Markdown to PDF
        run: pandoc temp_cv.md -o latest-output/cv_garthmortensen.pdf --pdf-engine=pdflatex --variable=colorlinks:true --variable=linkcolor:blue --variable=urlcolor:blue

      - name: Convert Markdown to DOCX
        run: pandoc temp_cv.md -o latest-output/cv_garthmortensen.docx --reference-links

      - name: Clean up temporary file
        run: rm temp_cv.md

      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Resume
          body: "Automatically generated resume files"
          files: |
            latest-output/cv_garthmortensen.pdf
            latest-output/cv_garthmortensen.docx
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}