name: Convert Markdown to pdf and docx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra

      - name: Create output directory
        run: mkdir -p latest-output

      - name: Add timestamp and commit hash to CV
        run: |
          TIMESTAMP=$(date -u '+%Y-%m-%d')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          
          # Add timestamp and commit info right after the name with clickable commit link
          sed -i "2i\\Last updated: ${TIMESTAMP} | Commit: [${COMMIT_HASH}](https://github.com/garthmortensen/cv/commit/${COMMIT_HASH})\n" cv.md

      - name: Copy CV to README
        run: cp cv.md README.md

      - name: Convert Markdown to PDF
        run: pandoc cv.md -o latest-output/cv_garthmortensen.pdf --pdf-engine=pdflatex --variable=colorlinks:true --variable=linkcolor:blue --variable=urlcolor:blue

      - name: Convert Markdown to DOCX
        run: pandoc cv.md -o latest-output/cv_garthmortensen.docx --reference-links

      - name: Commit files to the repo
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add cv.md README.md latest-output/cv_garthmortensen.pdf latest-output/cv_garthmortensen.docx
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Automated CV update with timestamp and generated files [skip ci]'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}