name: Convert Markdown to PDF and DOCX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra

      - name: Create output directory
        run: mkdir -p latest-output

      - name: Copy README to output directory
        run: cp README.md latest-output/cv_garthmortensen.md

      - name: Convert Markdown to PDF
        run: pandoc README.md -o latest-output/cv_garthmortensen.pdf --pdf-engine=pdflatex --variable=colorlinks:true --variable=linkcolor:blue --variable=urlcolor:blue

      - name: Convert Markdown to DOCX
        run: pandoc README.md -o latest-output/cv_garthmortensen.docx --reference-links

      - name: Commit files to the repo
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add latest-output/cv_garthmortensen.md latest-output/cv_garthmortensen.pdf latest-output/cv_garthmortensen.docx
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Automated CV update and file generation [skip ci]'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}